version: 0.2

proxy:
    upload-artifacts: yes
    logs: yes

phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      # Upgrade AWS CLI to the latest version
      - pip install --upgrade awscli
  build:
    commands:
      - echo "Starting SAM packaging"
      - aws cloudformation package --template-file template.yaml --s3-bucket genx-test-lambda --output-template-file packaged.yaml --debug
  post_build:
    commands:
      - echo "SAM packaging completed"

artifacts:
  type: zip
  files:
    - template.yaml
    - packaged.yaml